name: Testing Trigger - workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the person to greet"
        required: true
        type: string
      age:
        description: "Age of the person to greet"
        required: false
        type: number
        default: 0

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: |
          echo "Hello, ${{ inputs.name }}!"
          echo "You are ${{ inputs.age }} years old."
